apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: knowage
  name: knowage
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: 'flopez/knowage:6.2.0-s'
      from:
        kind: DockerImage
        name: 'flopez/knowage:6.2.0-s'
      generation: null
      importPolicy: {}
      name: 6.2.0-s
      referencePolicy:
        type: Source
status:
  dockerImageRepository: ''
